---
- name: Restart gitlab
  listen: restart gitlab
  ansible.builtin.command: gitlab-ctl reconfigure
  register: gitlab_restart
  failed_when: gitlab_restart_handler_failed_when | bool
  changed_when: gitlab_restart.rc == 0
